version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dartcli
    binary: dartcli
    ldflags:
      - -s -w
      - -X github.com/seapy/dartcli/pkg/dartcli.Version={{.Version}}
      - -X github.com/seapy/dartcli/pkg/dartcli.Commit={{.Commit}}
      - -X github.com/seapy/dartcli/pkg/dartcli.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: dartcli
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: seapy
    name: dartcli
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
